### ISSUE TITLE
ipv6 not working?

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd-tools#101]
I got this report:

> For me, if I try to connect using server name, it tries to use IPv6. smbd seems to listen only on IPv4.
> Client gets a TCP RST and desists. IPv4 work as expected

Can we verify that ipv6 works?

**Comment by Andy2244** [comment]
I think `netstat -tulpn` and `tcptrack -i eth0` shows the status.

**Comment by Andy2244** [comment]
@namjaejeon I just noticed the added ipv6 support in smbd thanks, can we get a userspace/smb config setting to enable disable ipv4/ipv6 explicitly. Maybe a command switch like `-4`, `-6` ? 
The reason is that some users prefer to run smb only in a local ipv6 only LAN setup and keep all outward/wan facing stuff in the compatible ipv4. 
Similar some users like to disable all ipv6 service stuff, so they dont have to worry about services leaking information without correct ipv6 firewall setup.

PS: Regarding the smbd -> ksmbd renaming, thats not a big issue for us (openWrt).

**Comment by namjaejeon** [comment]
@Andy2244 Ah, Is this new function that does not exist in samba ? Because I can't find similar one in smb.conf parameter list. 


> Similar some users like to disable all ipv6 service stuff, so they dont have to worry about services leaking information without correct ipv6 firewall setup.

Okay. I will take a look.

> PS: Regarding the smbd -> ksmbd renaming, thats not a big issue for us (openWrt).
Thanks!
