### ISSUE TITLE
DKMS Support

### ISSUE THREAD

**Issue by tuldok89** [cifsd-team/cifsd-tools#22]
Hello,

Is it possible to build this module using DKMS?

**Comment by sergey-senozhatsky** [comment]
On (04/08/19 08:16), Tuldok wrote:
>    Hello,
> 
>    Is it possible to build this module using DKMS?

Hi,

cifsd-tools is a user space daemon; cifsd is a kernel module
(so the issue should be moved)

As of DKMS - our current plan is to merge cifsd upstream at some
point this year (staging subtree). If we succeed then DKMS becomes
unnecessary, if we fail then we probably can take a look at DKMS.

	-ss
