### ISSUE TITLE
'interfaces' option and white-spaces separator

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd-tools#32]
Just stumbled over a small incompatibility compared to samba's smb.conf.

Samba accepts this and will bind to both interfaces.
`interfaces = lo br-lan`

Cifsd does not and will only bind to the loopback interface, without any additional errors. Maybe it even tries to bind to "lo br-lan", yet again no errors are given.

It would be nice if this option would additionally accept white-spaces as separators, since it took me a while to find this problem, while copy&pasting parameters.
This way it stays compatible to samba's smb.conf and our logic that dynamically creates the interfaces string list can stay the same.

PS: Not a big deal if you only want to allow `,` as separators on cifsd, just asking what you think, since so far most options are samba compatible.

**Comment by sergey-senozhatsky** [comment]
On (05/24/19 14:39), Andy Walsh wrote:
>    Just stumbled over a small incompatibility compared to samba's smb.conf.
> 
>    Samba accepts this and will bind to both interfaces.
>    interfaces = lo br-lan
> 
>    Cifsd does not and will only bind to the loopback interface, without any
>    additional errors. Maybe it even tries to bind to "lo br-lan", yet again
>    no errors are given.
> 
>    It would be nice if this option would accept white-spaces as separators,
>    since it took me a while to find this problem, while copy&pasting
>    parameters. This way it stays compatible to samba's smb.conf and our logic
>    that dynamically creates the interfaces string list can stay the same.

Hello,

OK, will take a look.

	-ss

**Comment by sergey-senozhatsky** [comment]
Sent two patch sets, convering interfaces list to a common list API... Finally.

-ss

**Comment by sergey-senozhatsky** [comment]
@Andy2244 I'm a bit confused. I suppose you actually meant that we support only white-space separators for IF list ' '. While samba requires us to also support \t and ','. And that's what was missing. Correct?

**Comment by Andy2244** [comment]
@sergey-senozhatsky Yes my main concern was to reduce errors converting from samba to cifsd, so white-space should be the minimal support. Yet cifsd itself uses `,` for all it other list options, so its not unreasonable to expect that IF list also supports those to stay consistent?

**Comment by sergey-senozhatsky** [comment]
@Andy2244 The inconsistency which I see is that we had supported only white-space separators for IF list.
As of now IF list can contain `whitespace ' ' comma , tab \t`, just like the rest of smb.conf lists. Does that work
for you?

**Comment by Andy2244** [comment]
> Does that work for you?

Sure that's fine, will update if merged to master, thanks.

**Comment by namjaejeon** [comment]
@Andy2244  I pushed all to master now. Thanks for your work!

**Comment by Andy2244** [comment]
@sergey-senozhatsky The changes do not work for me?

```
[global]
	netbios name = router
	server string = Cifsd on OpenWrt
	workgroup = WORKGROUP
	interfaces = lo br-lan tap_soft
	bind interfaces only = yes
	ipc timeout = 8
	deadtime = 15
	map to guest = Bad User

[sharetest]
	path = /tmp/etc
	create mask = 0666
	directory mask = 0777
	guest ok = yes
```

I tried to bind to those 3 interfaces (`br-lan tap_soft lo`).
I also noticed that changes to the interface might not be reflected without removing the module?
so i used this for all tests: `rmmod cifsd ; modprobe cifsd ; cifsd --n`

Fails:
```
interfaces = lo br-lan
interfaces = br-lan tap_soft lo
interfaces = tap_soft br-lan
```

Works:
```
interfaces = br-lan
interfaces = br-lan lo
interfaces = br-lan tap_soft
```

So it seems depending on where i put the `lo` interface it will fail and also it does not work if the main interface i test for `br-lan` is not the first one?

**Comment by sergey-senozhatsky** [comment]
On (06/18/19 03:07), Andy Walsh wrote:
>    [1]@sergey-senozhatsky The changes do not work for me?
> 
>  [global]
>          netbios name = router
>          server string = Cifsd on OpenWrt
>          workgroup = WORKGROUP
>          interfaces = lo br-lan tap_soft
>          bind interfaces only = yes
>          ipc timeout = 8
>          deadtime = 15
>          map to guest = Bad User
> 
>  [sharetest]
>          path = /tmp/etc
>          create mask = 0666
>          directory mask = 0777
>          guest ok = yes
> 
>    I tried to bind to those 3 interfaces (br-lan tap_soft lo).
>    I also noticed that changes to the interface might not be reflected
>    without removing the module?
>    so i used this for all tests: rmmod cifsd ; modprobe cifsd ; cifsd --n

We never supported hot-plug/unplug of intercase. Once kcifsd has been
initialized we don't support full server re-configuration.

>    Fails:
> 
>  interfaces = lo br-lan
>  interfaces = br-lan tap_soft lo
>  interfaces = tap_soft br-lan
> 
>    Works:
> 
>  interfaces = br-lan
>  interfaces = br-lan lo
>  interfaces = br-lan tap_soft
> 
>    So it seems depending on where i put the lo interface it will fail and
>    also it does not work if the main interface i test for br-lan is not the
>    first one?

Need to check if SO_BINDTODEVICE supports multiple interfaces.

include/net/sock.h

	@skc_bound_dev_if: bound device index if != 0

	struct sock_common {
	...
		int				skc_bound_dev_if;
	...
	};

I think that we can't bind socket to multiple interfaces...

	-ss

**Comment by sergey-senozhatsky** [comment]
Hmm... Could be the case that we actually need to create sockets per-interface and bind sockets to particular interfaces only, so there is a 1:1 relation.

-ss

**Comment by Andy2244** [comment]
> I think that we can't bind socket to multiple interfaces...

Should not be a big problem for most openwrt users, but than why try make it a list in the fist place?

**Comment by sergey-senozhatsky** [comment]
> Should not be a big problem for most openwrt users, but than why try make it a list in the fist place?

I didn't write that code, so can't really answer.
The assumption was that SO_BINDTODEVICE supports a list of interfaces the socket should bind to,
I suppose.

> This also means bind interfaces only = yes is kinda redundant, if we can only bind to one anyway?

Yes. Honestly, I don't get the meaning of "bind interfaces only". I'd rather remove it.

So we can either change it to a "single interface only" or move towards "socket per-interface" solution.
In any case "bind interfaces only" is confusing and pointeless.

-ss

**Comment by Andy2244** [comment]
> In any case "bind interfaces only" is confusing and pointless.

I'm also not sure how `interfaces` behaves in samba, if `bind interfaces only` is not set to `yes`?
https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#INTERFACES
https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#BINDINTERFACESONLY

In our case if cifsd does not yet support binding to multiple network interfaces, than this should happen:
- remove `bind interfaces only`
- rename `interfaces` to `interface`, to make this clear 
- without `interface` cifsd should try to find the LAN-BR/LAN interface by default and bind to it, filter external IP, loopback, VPN ranges.
- if `interface` is specified, try bind to it and print a error if it cant find the interface or the bind fails.

If we want to support multiple interfaces
- remove `bind interfaces only`
- only bind to one LAN interface by default
- accept a list of interfaces

**Comment by namjaejeon** [comment]
@Andy2244 Hm.. I want to find more ways to support multiple devices. Thanks for your opinion and report. please wait a little more.

**Comment by Andy2244** [comment]
Any update on this?

**Comment by namjaejeon** [comment]
@Andy2244 Sorry for late response. Currently I am busy to check other urgent issue. I think that I will start to check it this week. and hopefully get any conclusion soon.

**Comment by namjaejeon** [comment]
@Andy2244 I am thinking this issue is fixed with this patch(https://github.com/cifsd-team/cifsd/commit/678ab7ae1e4f11ccaa7adc527c5c076ae13934a0)
You can check this issue with cifsd-next. We need to a little more time to push them to master.

**Comment by namjaejeon** [comment]
@Andy2244 I pushed all patches to mater now. please check!
Thanks!

**Comment by Andy2244** [comment]
@namjaejeon ok just did a quick test and now i see one process per interface and my failing testcase of  `interfaces = lo br-lan` now works.

thanks
