### ISSUE TITLE
Update Version string on changesets.

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd-tools#39]
It would be helpfully to actually increase the cifsd Version numbering, so we can make sure to have the "correct" version that corresponds to a specific changeset/timeline.

So ideally cifsd -h should print a version number for the tools and kmod and/or the github commit hash/date.
```
cifsd -h
cifsd-tools version : 2.0.0
```
vs
```
cifsd -h
cifsd-tools version : 2.0.1 (git-2019-06-18, commit-81e4ff3)
cifsd-kmod version: 2.0.1 (git-2019-06-18, commit-05cc2b1)
```

**Comment by namjaejeon** [comment]
Yep, I will do that.
Thanks for your suggestion!

**Comment by Andy2244** [comment]
Still an issue btw

**Comment by namjaejeon** [comment]
Sorry, I will back cifsd work soon. and will fix it first :)
Thanks!

**Comment by sergey-senozhatsky** [comment]
On (19/06/18 05:13), Namjae Jeon wrote:
>    Yep, I will do that.
>    Thanks for your suggestion!

I sent a patch, which generates version string with some git magic.
It relies on the fact that cifsd-tools is built from the .git tree.

Example:

$ ./cifsd/cifsd -v
cifsd-tools version : 2.0.0 7e5e6f8

---

 configure.ac | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

diff --git a/configure.ac b/configure.ac
index 312d5dd..3e16590 100755
--- a/configure.ac
+++ b/configure.ac
@@ -5,12 +5,15 @@ m4_define([cifsd_tools_minor_ver], [0])
 m4_define([cifsd_tools_micro_ver], [0])
 
 m4_define([cifsd_tools_version],
-	  [cifsd_tools_major_ver.cifsd_tools_minor_ver.cifsd_tools_micro_ver])
+	[cifsd_tools_major_ver.cifsd_tools_minor_ver.cifsd_tools_micro_ver])
 
-AC_INIT([CIFSD tools], [cifsd_tools_version],
+AC_INIT([CIFSD tools],
+	[m4_esyscmd_s([git describe --abbrev=7 --dirty --always --tags])],
 	[linux-cifsd-devel@lists.sourceforge.net])
 
-AC_DEFINE([CIFSD_TOOLS_VERSION], "cifsd_tools_version", [cifsd-tools version])
+AC_DEFINE([CIFSD_TOOLS_VERSION],
+	"cifsd_tools_version [m4_esyscmd_s([git describe --abbrev=7 --dirty --always --tags])]",
+	["cifsd-tools version"])
 
 AC_CONFIG_SRCDIR([config.h.in])
 AC_CONFIG_HEADER([config.h])
-- 
2.24.0

**Comment by sergey-senozhatsky** [comment]
Note, that I use a statically defined 
        [cifsd_tools_major_ver.cifsd_tools_minor_ver.cifsd_tools_micro_ver]
in this patch. 

-ss

**Comment by sergey-senozhatsky** [comment]
I sent out an updated configure script. If we will start tagging cifsd-tools releases
then we can remove major.minor static defines from configure.ac

-ss

**Comment by namjaejeon** [comment]
pushed the patches to master branch.
@Andy2244 could you please check it ?

Thanks!

**Comment by Andy2244** [comment]
mhh i get this from latest commit: 0e17afffe8725fabe6e9209e34d8c7c2759353e4
`cifsd-tools version : 2.0.0 reboot-11546-ga74095c68c`

How do i use those version numbers to get back to the actual commit that was used to build it? I also think a date would be nice as a quick check.

**Comment by sergey-senozhatsky** [comment]
On (19/11/19 11:49), Andy Walsh wrote:
> mhh i get this from latest commit: 0e17afffe8725fabe6e9209e34d8c7c2759353e4
> `cifsd-tools version : 2.0.0 reboot-11546-ga74095c68c`

The last object id is a74095c68c. The leading 'g' is just how git tells
us "hi". That number right before the last object id, is supposedly the
number of commits that you have atop of "last known tag".

But... the output which you have looks a bit strange to me.
I think things should change once you tag a commit.

We should start tagging the -master branch releases (both for
cifsd-tools and kcifsd).



EXAMPLE:

$ git tag v2.0.0
$ git describe --tags --dirty --always --long
v2.0.0-0-g01162e6

So here we go.

- The last tag was v2.0.0
- I have zero commits atop of "tagged" commit (no local modifications)
- We used git tree (that's what 'g' is for)
- The HEAD commit id was 01162e6

That sounds slightly more informative than 'date'.



If I do local modifications, but don't commit them, then the version
string will contain "-dirty" mark:

$ ./cifsd/cifsd -v
cifsd-tools version : v2.0.0-0-g01162e6-dirty

If I commit those changes, then the version string should become:

$ ./cifsd/cifsd -v
cifsd-tools version : v2.0.0-1-g79ddf8e

Notice, that now we have "1" commit atop of tagged commit.


Do things look similar for you once you tag the release?


NOTE, with properly tagged releases we need to do the following:

===8<===8<===

From: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
Subject: [PATCH] cifsd-tools: do not add statically defined version

We need tags

Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
---
 configure.ac | 9 +--------
 1 file changed, 1 insertion(+), 8 deletions(-)

diff --git a/configure.ac b/configure.ac
index 2d7165e..15b0cbd 100755
--- a/configure.ac
+++ b/configure.ac
@@ -1,18 +1,11 @@
 AC_PREREQ([2.68])
 
-m4_define([cifsd_tools_major_ver], [2])
-m4_define([cifsd_tools_minor_ver], [0])
-m4_define([cifsd_tools_micro_ver], [0])
-
-m4_define([cifsd_tools_version],
-	[cifsd_tools_major_ver.cifsd_tools_minor_ver.cifsd_tools_micro_ver])
-
 AC_INIT([CIFSD tools],
 	[m4_esyscmd_s([git describe --tags --dirty --always --long || echo unknown])],
 	[linux-cifsd-devel@lists.sourceforge.net])
 
 AC_DEFINE([CIFSD_TOOLS_VERSION],
-	"cifsd_tools_version [m4_esyscmd_s([git describe --tags --dirty --always --long || echo unknown])]",
+	"[m4_esyscmd_s([git describe --tags --dirty --always --long || echo unknown])]",
 	["cifsd-tools version"])
 
 AC_CONFIG_SRCDIR([config.h.in])
-- 
2.24.0.432.g9d3f5f5b63-goog

**Comment by Andy2244** [comment]
I can just speak from my experience, but i like tagged releases that are easy to find on github or direct git commit hashes or shortened version of it. Mainly i just want a quick/direct way to jump to the commit/branch/tag of a build version using github.

As example docker shows this as version info:
```
Docker version master-dockerproject-2019-11-18, build 6c12a82f
Docker version 19.03.2, build 6a30dfca03664a0b6bf0646a7d389ee7d0318e6e
```

**Comment by Andy2244** [comment]
I just noticed that it would be nice to add a actual "-V" version switch to the cifsd-tool, so we can easily get the version info from the stdout.
I prefer the short samba output, since we can directly use this string, without additional parsing.
```
root@router:~# smbd -V
Version 4.9.15
```

**Comment by namjaejeon** [comment]
Version numbering with git tags is a bit unfamiliar. When I checked other opensources(linux kernel, samba, filesystem tools), they didn't use this way. maybe git dependency ?  I think that statical version number may be the best way for now. I can increment manually whenever merging -next into master. If needed, I can add date also. And regarding kmod version, I will add a function that show cifsd version through /sysfs or /proc.

**Comment by Andy2244** [comment]
> When I checked other opensources(linux kernel, samba, filesystem tools), they didn't use this way. maybe git dependency ?

Probably, most have actual releases they tag/branch. I guess if the code stabilizes more you could also just tag releases, so we can either pick a "stable" or "latest" release for our builds.

I just added cifsd to the first "stable" rc1 branch for the "soonish" (next year) release. So i hope we get more feedback and bug reports this way, since ultimately cifsd will replace samba3 for us.

**Comment by sergey-senozhatsky** [comment]
On (19/11/25 04:15), Namjae Jeon wrote:
>    Version numbering with git tags is a bit unfamiliar. When I checked other
>    opensources(linux kernel, samba, filesystem tools), they didn't use this
>    way. maybe git dependency ?

Linux does use git describe.
Check scripts/setlocalversion in the Linux source tree.

	-ss

**Comment by sergey-senozhatsky** [comment]
On (19/11/25 04:15), Namjae Jeon wrote:
>    And regarding kmod version, I will
>    add a function that show cifsd version through /sysfs or /proc.

Please don't. Just add MODULE_VERSION() to server.c

	-ss

**Comment by namjaejeon** [comment]
> Linux does use git describe.
> Check scripts/setlocalversion in the Linux source tree.
When we download kernel compressed by tar.gz, It contain git info to get version number catch ?
Other opensource official release is compressed file that doesn't contain git ?
and cifsd.zip also can be downloaded by "clone or download" in github. and cifsd.zip file doesn't contain .git files. So I think that we should manage both git tag and statical version number.

**Comment by namjaejeon** [comment]
> PS: I just added cifsd to the first "stable" openwrt rc1 branch for the "soonish" (next year) release. So i hope we get more feedback and bug reports this way, since ultimately cifsd will replace samba3 for us.

Great news! We will fully support your work :)
Thanks for your work!

**Comment by namjaejeon** [comment]
> Please don't. Just add MODULE_VERSION() to server.c

How does openwrt take kcifsd version if we just use MODULE_VERSION() ?

**Comment by sergey-senozhatsky** [comment]
On (19/11/26 16:32), Namjae Jeon wrote:
>      Please don't. Just add MODULE_VERSION() to server.c
> 
>    How does openwrt take kcifsd version if we just use MODULE_VERSION() ?
> 

MODULE_VERSION puts a version string into a dedicated ELF section.
Which means that there are numerous ways to read the version string,
one of them is `modinfo kcifsd'.

	-ss

**Comment by namjaejeon** [comment]
@Andy2244 I added v2.0.2 and v2.0.1 tag on mater branch. Could you check ?
Thanks!

**Comment by namjaejeon** [comment]
> MODULE_VERSION puts a version string into a dedicated ELF section.
Which means that there are numerous ways to read the version string,
one of them is `modinfo kcifsd'.

It seems okay if cifsd doesn't built-in kernel.
@Andy2244 Any opinion ?

**Comment by namjaejeon** [comment]
@Andy2244 I added mod version to cifsd.ko. You can see cifsd.ko version using modinfo. Let me know your opinion.

**Comment by Andy2244** [comment]
Ok i get this for cifsd.ko from latest master?
```
modinfo cifsd
module:         /lib/modules/4.19.85/cifsd.ko
softdep:        pre: gcm
softdep:        pre: ccm
softdep:        pre: aead2
softdep:        pre: sha512
softdep:        pre: sha256
softdep:        pre: cmac
softdep:        pre: aes
softdep:        pre: nls
softdep:        pre: md5
softdep:        pre: md4
softdep:        pre: hmac
softdep:        pre: ecb
softdep:        pre: des
softdep:        pre: arc4
license:        GPL
depends:
name:           cifsd
vermagic:       4.19.85 SMP mod_unload ARMv7 p2v8
```
I still don't see any -h help or -v version cmd option, the output is still error output, instead of stdout.
```
cifsd -v
cifsd-tools version : 2.0.2 reboot-11595-g5d2a900163
Usage: cifsd
        --p=NUM | --port=NUM              TCP port NUM
        --c=smb.conf | --config=smb.conf  config file
        --u=pwd.db | --users=pwd.db       Users DB
        --n | --nodetach                  Don't detach
        --s | --systemd                   Service mode
```
So something basic like `cifsd -v | grep version` can't work and i still need to have a special case just to extract cifsd version from errout.

I would expect this to work as normal stdout:
```
cifsd -v
cifsd-tools version : 2.0.2 reboot-11595-g5d2a900163
```
and
```
cifsd -h
Usage: cifsd
        --p=NUM | --port=NUM              TCP port NUM
        --c=smb.conf | --config=smb.conf  config file
        --u=pwd.db | --users=pwd.db       Users DB
        --n | --nodetach                  Don't detach
        --s | --systemd                   Service mode
        -v show version
        -h show help
```

**Comment by namjaejeon** [comment]
Have you checked the latest master ?

[linkinjeon@localhost cifsd]$ modinfo ./cifsd.ko 
filename:       /home/linkinjeon/git/cifsd/cifsd/./cifsd.ko
softdep:        pre: gcm
softdep:        pre: ccm
softdep:        pre: aead2
softdep:        pre: sha512
softdep:        pre: sha256
softdep:        pre: cmac
softdep:        pre: aes
softdep:        pre: nls
softdep:        pre: md5
softdep:        pre: md4
softdep:        pre: hmac
softdep:        pre: ecb
softdep:        pre: des
softdep:        pre: arc4
license:        GPL
description:    Linux kernel CIFS/SMB SERVER
version:        2.0.2
author:         Namjae Jeon <linkinjeon@gmail.com>
srcversion:     75A3C54D6FC0556F2A56AA8
depends:        
retpoline:      Y
name:           cifsd
vermagic:       5.3.11-200.fc30.x86_64 SMP mod_unload

**Comment by Andy2244** [comment]
Yes its b8675c8a...?
```
 modinfo ./build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu_cortexa9/cifsd-2019-11-27-b8675c8a/cifsd.ko
filename:       /root/openwrt/./build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu_cortexa9/cifsd-2019-11-27-b8675c8a/cifsd.ko
softdep:        pre: gcm
softdep:        pre: ccm
softdep:        pre: aead2
softdep:        pre: sha512
softdep:        pre: sha256
softdep:        pre: cmac
softdep:        pre: aes
softdep:        pre: nls
softdep:        pre: md5
softdep:        pre: md4
softdep:        pre: hmac
softdep:        pre: ecb
softdep:        pre: des
softdep:        pre: arc4
license:        GPL
depends:
name:           cifsd
vermagic:       4.19.85 SMP mod_unload ARMv7 p2v8

```

**Comment by namjaejeon** [comment]
OpenWRT seems to use busybox instead of util-linux ?

**Comment by Andy2244** [comment]
> OpenWRT seems to use busybox instead of util-linux ?

Yes, but i get the same in my Debian 9 Dev-VM from its modinfo on the build kmod and have util-linux
installed there?

**Comment by namjaejeon** [comment]
Okay, Let me consider mod version print through /sysfs.

> I would expect this to work as normal stdout:

Okay, I WILL.

**Comment by Andy2244** [comment]
> /sysfs.

I guess this would rely on a loaded kernel module?
The UI where the version info is displayed does not strictly rely on a running service. So its a bit weird that the kmod version is only displayed on a running service, but at least we always get the cifsd-tools version.

**Comment by namjaejeon** [comment]
> I guess this would rely on a loaded kernel module?

Yes.

> at least we always get the cifsd-tools version.
Let me think.

**Comment by Andy2244** [comment]
ok just got the info, that yes we strip metadata, but there is a way to explicitly preserve it.
Gimme some minutes to verify this.

**Comment by Andy2244** [comment]
ok its working now via adding this to glob.h:
`#undef CONFIG_MODULE_STRIPPED`

```
modinfo ./build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu_cortexa9/cifsd-2019-11-27-b8675c8a/cifsd.ko
filename:       /root/openwrt/./build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu_cortexa9/cifsd-2019-11-27-b8675c8a/cifsd.ko
softdep:        pre: gcm
softdep:        pre: ccm
softdep:        pre: aead2
softdep:        pre: sha512
softdep:        pre: sha256
softdep:        pre: cmac
softdep:        pre: aes
softdep:        pre: nls
softdep:        pre: md5
softdep:        pre: md4
softdep:        pre: hmac
softdep:        pre: ecb
softdep:        pre: des
softdep:        pre: arc4
license:        GPL
description:    Linux kernel CIFS/SMB SERVER
version:        2.0.2
author:         Namjae Jeon <linkinjeon@gmail.com>
srcversion:     6B0CEF3528E327305390313
depends:
name:           cifsd
vermagic:       4.19.85 SMP mod_unload ARMv7 p2v8
```

**Comment by sergey-senozhatsky** [comment]
> Okay, Let me consider mod version print through /sysfs.

Inserting and initialising the module (running sysfs initialization, making user-space visible fs nodes, and so and on and on) in order to just read the module version - is bizarre.

**Comment by namjaejeon** [comment]
@Andy2244 release v2.0.3 version. please check it.

**Comment by Andy2244** [comment]
@namjaejeon ok looks good now, thx
