### ISSUE TITLE
static glib2 build option?

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd-tools#74]
I just wondered if a static glib2 linking option could reduce size, since in its minimal setup we at OpenWrt just need `sbin/cifsd` since most will use it as simple fileserver so user management is not needed and we also build our own smb.conf via template so addshare is also not needed.

Just wondering what the size of a static glib2 linked + stripped sbin/cifsd would be. We want it to replace samba3 for older 8/16 MB nvram devices so maybe that's something we could try?

**Comment by sergey-senozhatsky** [comment]
On (19/11/19 13:00), Andy Walsh wrote:
>    I just wondered if a static glib2 linking option could reduce size, since
>    in its minimal setup we at OpenWrt just need sbin/cifsd since most will
>    use it as simple fileserver so user management is not needed and we also
>    build our own smb.conf via template so addshare is also not needed.

Well, cifsshareadd/cifsuseradd binaries are not that large

	$ lh cifsshareadd/.libs/
	....    48K Nov 20 11:41 cifsshareadd

	$ lh cifsuseradd/.libs/
	....  116K Nov 20 11:41 cifsuseradd

I can, probably, add configure knobs to disable/enable them. But
it doesn't look like we are going to save a lot.

Statically compiled glib2... might be interesting. Could you run
some experiments to see if we save enough?

	-ss

**Comment by Andy2244** [comment]
> Statically compiled glib2... might be interesting. Could you run some experiments to see if we save enough?

I would, but i just glanced over the automake documentation and had problems quickly figuring out how to set glib static. I think its the LDFLAGS or LDADD option, but i thought this should be trivial for you guys.

PS: Keep in mind i'm mainly a gamedev so all the Linux stuff is my hobby and mostly i worked with cmake.

**Comment by sergey-senozhatsky** [comment]
On (19/11/20 03:26), Andy Walsh wrote:
>      Statically compiled glib2... might be interesting. Could you run some
>      experiments to see if we save enough?
> 
>    I would, but i just glanced over the automake documentation and had
>    problems quickly figuring out how to set glib static. I think its the
>    LDFLAGS or LDADD option, but i thought this should be trivial for you
>    guys.
> 
>    PS: Keep in mind i'm mainly a gamedev so all the Linux stuff is my hobby
>    and mostly i worked with cmake.

Got it. I'll try to come up with a test patch (in a day or two).

	-ss

**Comment by Andy2244** [comment]
@sergey-senozhatsky ok i did dig into libtool a bit and managed to get a static cifsd out via:

cifsd/makefile.am
```
AM_CFLAGS = -I$(top_srcdir)/include $(GLIB_CFLAGS) $(LIBNL_CFLAGS) -fno-common
AM_LDFLAGS = -all-static
LIBS = $(GLIB_LIBS) $(LIBNL_LIBS) -liconv
cifsd_LDADD = $(top_builddir)/lib/libcifsdtools.la

sbin_PROGRAMS = cifsd

cifsd_SOURCES = worker.c ipc.c rpc.c rpc_srvsvc.c rpc_wkssvc.c cifsd.c
```
The only way that worked for me was the `-all-static` option?

The size difference is neglect-able for normal systems, while on 4/8MB nvram embedded devices this may be the difference on getting smb3 + vpn working vs having to choose one over the other.

compressed size diffs for arm only (kmod + cifsd):
310kb (cifsd static)
570kb (samba3)
810kb (cifsd shared)

So you can save 500kb of firmware size, that can be used for other services.

PS: The only problem is that without a multicall (aka busybox like) binary you cant create user passwords or have to add the cifsuseradd into temp/ram create the password db and remove it again.

**Comment by sergey-senozhatsky** [comment]
On (19/12/07 15:00), Andy Walsh wrote:
>    [1]@sergey-senozhatsky ok i did dig into libtool a bit and managed to get
>    a static cifsd out via:
>
>    cifsd/makefile.am
>
>  AM_CFLAGS = -I$(top_srcdir)/include $(GLIB_CFLAGS) $(LIBNL_CFLAGS) -fno-common
>  AM_LDFLAGS = -all-static
>  LIBS = $(GLIB_LIBS) $(LIBNL_LIBS) -liconv
>  cifsd_LDADD = $(top_builddir)/lib/libcifsdtools.la
>
>  sbin_PROGRAMS = cifsd
>
>  cifsd_SOURCES = worker.c ipc.c rpc.c rpc_srvsvc.c rpc_wkssvc.c cifsd.c
>
>    The only way that worked for me was the -all-static option?

I managed to compile only with "all-static" as well. But -static
libc is hardly what we need.

It seems that there are ways to tell libtool to statically link specific
libraries only, but none of those ways worked for me so far.

>    The size difference is neglect-able for normal systems, while on 4/8MB
>    nvram embedded devices this may be the difference on getting smb3 + vpn
>    working vs having to choose one over the other.
>
>    compressed size diffs for arm only (kmod + cifsd):
>    310kb (cifsd static)
>    570kb (samba3)
>    810kb (cifsd shared)
>
>    So you can save 500kb of firmware size, that can be used for other
>    services.

That's with -all-static, right? So we carry around statically linked
pthread and libc code.

	-ss

**Comment by sergey-senozhatsky** [comment]
@Andy2244, by the way, do you optimize cifsd binary for size

` ./configure CFLAGS='-Os'`

This can save some bits here and there.

-ss

**Comment by Andy2244** [comment]
> `./configure CFLAGS='-Os'`
> 
> This can save some bits here and there.

Sure openwrt enables this by default and only a few packages explicitly override this.
https://github.com/openwrt/openwrt/blob/master/include/target.mk

**Comment by Andy2244** [comment]
> That's with -all-static, right? So we carry around statically linked pthread and libc code.

Yes, i also managed to build static without patching the makefile.am files:
```
CONFIGURE_ARGS += \
	--disable-shared \
	--enable-static

TARGET_CFLAGS += $(if $(CONFIG_PACKAGE_glib2),,-static)
TARGET_LDFLAGS += $(if $(CONFIG_PACKAGE_glib2),,--static)
```

> It seems that there are ways to tell libtool to statically link specific libraries only, but none of those ways worked for me so far.

Yeah had the same problem, seems like a issue with libtool. I settled with splitting our package, so by default i now build cifsd static and users have to separately install the other tools. This works for guest only servers or if you have already created your user database file. We don't use the share tool, since my inti script does all the smb.conf stuff.
This way adding my static 'cifsd-server' package to the firmware image is just 310kb in total, including the kmod. In comparison samba4 needs 6MB, so its a really big advantage. I also suspect samba4 will always just grow bigger, since they are not interested in providing a minimal fileserver only build option.

**Comment by sergey-senozhatsky** [comment]
On (19/12/09 02:47), Andy Walsh wrote:
>      That's with -all-static, right? So we carry around statically linked
>      pthread and libc code.
> 
>    Yes, i also managed to build static without patching the makefile.am
>    files:
> 
>  CONFIGURE_ARGS += \
>          --disable-shared \
>          --enable-static
> 
>  TARGET_CFLAGS += $(if $(CONFIG_PACKAGE_glib2),,-static)
>  TARGET_LDFLAGS += $(if $(CONFIG_PACKAGE_glib2),,--static)
> 
>      It seems that there are ways to tell libtool to statically link specific
>      libraries only, but none of those ways worked for me so far.
> 
>    Yeah had the same problem, seems like a issue with libtool. I settled with
>    splitting our package, so by default i now build cifsd static and users
>    have to separately install the other tools.

So... just for fun.

I added a --with-static-glib2=yes/--with-static-glib2=no configure param.
/* similar can be done for libnl */.

Example:

    ./autogen.sh; ./configure --with-static-glib2=yes

With static-glib2=yes, libtool sees that glib2 should be static:

  ... -Wl,-dn -Wl,-lglib-2.0 -pthread -pthread -Wl,-dy  ../lib/.libs/libcifsdtools.so -lpcre -lnl-genl-3 -lnl-3 -pthread

Notice that we switch ld to -static only for -lglib. The rest remains -dynamic.

But... That's very hacky and dirty.

---

 configure.ac    | 20 ++++++++++++++++++--
 lib/Makefile.am |  3 +--
 2 files changed, 19 insertions(+), 4 deletions(-)

diff --git a/configure.ac b/configure.ac
index 15b0cbd..b7317e6 100755
--- a/configure.ac
+++ b/configure.ac
@@ -41,11 +41,27 @@ AC_CHECK_FUNCS_ONCE([
 	recvmsg
 ])
 
-PKG_CHECK_MODULES([GLIB], [glib-2.0 >= 2.40], [has_glib2=1], [has_glib2=0])
+AC_ARG_WITH(static-glib2,
+	    [--without-static-glib2	Link with glib2 shared object],
+	    [with_glib2a=$withval],
+	    [with_glib2a=no])
+
+if test "x$with_glib2a" == xyes; then
+	dnl Static glib2
+	PKG_CHECK_MODULES_STATIC([GLIB], [glib-2.0 >= 2.40], [has_glib2=1], [has_glib2=0])
+	GLIB_LIBS=$(echo $GLIB_LIBS | sed -e s/-lglib/-Wl,-dn,-lglib/g)
+	GLIB_LIBS="$GLIB_LIBS -Wl,-dy"
+else
+	dnl Dynamic glib2
+	PKG_CHECK_MODULES([GLIB], [glib-2.0 >= 2.40], [has_glib2=1], [has_glib2=0])
+fi
+
 AS_IF([test "$has_glib2" -eq 0],
-      AC_MSG_ERROR([No glib2 (libglib2.0-dev) was found])
+	AC_MSG_ERROR([No glib2 (libglib2.0-dev) was found])
 ])
 
+AC_SUBST(GLIB_LIBS)
+
 has_libnl_ver=0
 dnl libnl-genl-3.0.pc pkg-config file just for libnl-3.0 case.
 PKG_CHECK_MODULES([LIBNL], [libnl-3.0 >= 3.0 libnl-genl-3.0 >= 3.0], [has_libnl_ver=3], [has_libnl_ver=0])
diff --git a/lib/Makefile.am b/lib/Makefile.am
index 894497b..3b967df 100644
--- a/lib/Makefile.am
+++ b/lib/Makefile.am
@@ -1,8 +1,7 @@
 AM_CFLAGS = -I$(top_srcdir)/include $(GLIB_CFLAGS) -fno-common
-LIBS = $(GLIB_LIBS)
+LIBS = $(GLIB_LIBS) -lresolv
 
 lib_LTLIBRARIES = libcifsdtools.la
-libcifsdtools_la_LIBADD = -lresolv
 libcifsdtools_la_SOURCES = management/tree_conn.c \
 			   management/user.c \
 			   management/share.c \

**Comment by Andy2244** [comment]
mhh your patch made the cifsd actually bigger?
Full static cifsd binary is 662kb, while with your patch i get 572kb for the lib + 553kb for cifsd?

Can you add a option to also link libcifsdtools static? 
If i try add:
`./configure --disable-shared --enable-static --with-static-glib2=yes`
i get errors with missing calls into gio-2.0?

```
/bin/bash ../libtool  --tag=CC   --mode=link arm-openwrt-linux-muslgnueabi-gcc -I../include -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/include/glib-2.0 -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/glib-2.0/include -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/include/libnl3 -fno-common -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -ffile-prefix-map=/root/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/cifsd-tools-2019-11-30-830cba08=cifsd-tools-2019-11-30-830cba08 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libiconv-stub/include -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libintl-stub/include   -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/lib -L/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/usr/lib -L/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/lib -znow -zrelro -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libiconv-stub/lib -Wl,-rpath-link=/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libiconv-stub/lib -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libintl-stub/lib -Wl,-rpath-link=/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libintl-stub/lib  -o cifsd worker.o ipc.o rpc.o rpc_srvsvc.o rpc_wkssvc.o cifsd.o ../lib/libcifsdtools.la -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib -Wl,-dn,-lglib-2.0 -pthread -liconv -Wl,-dy -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib -lnl-genl-3 -lnl-3 -liconv
OpenWrt-libtool: link: arm-openwrt-linux-muslgnueabi-gcc -I../include -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/include/glib-2.0 -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/glib-2.0/include -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/include/libnl3 -fno-common -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -ffile-prefix-map=/root/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/cifsd-tools-2019-11-30-830cba08=cifsd-tools-2019-11-30-830cba08 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z -Wl,now -Wl,-z -Wl,relro -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libiconv-stub/include -I/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libintl-stub/include -znow -zrelro -Wl,-rpath-link=/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libiconv-stub/lib -Wl,-rpath-link=/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libintl-stub/lib -o cifsd worker.o ipc.o rpc.o rpc_srvsvc.o rpc_wkssvc.o cifsd.o -Wl,-dn -Wl,-lglib-2.0 -pthread -Wl,-dy  -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/lib -L/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/usr/lib -L/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/lib -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libiconv-stub/lib -L/root/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib/libintl-stub/lib ../lib/.libs/libcifsdtools.a -lresolv -lnl-genl-3 -lnl-3 -liconv -pthread
/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/8.3.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: ../lib/.libs/libcifsdtools.a(config_parser.o): in function `__mmap_parse_file':
config_parser.c:(.text+0x2ec): undefined reference to `g_mapped_file_new_from_fd'
/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/8.3.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: config_parser.c:(.text+0x348): undefined reference to `g_mapped_file_unref'
/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/8.3.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: config_parser.c:(.text+0x3a8): undefined reference to `g_mapped_file_get_contents'
/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/8.3.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: config_parser.c:(.text+0x3c0): undefined reference to `g_mapped_file_get_length'
/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/8.3.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: ../lib/.libs/libcifsdtools.a(cifsdtools.o): in function `base64_encode':
cifsdtools.c:(.text+0x170): undefined reference to `g_base64_encode'
/root/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-8.3.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/8.3.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: ../lib/.libs/libcifsdtools.a(cifsdtools.o): in function `base64_decode':
cifsdtools.c:(.text+0x17c): undefined reference to `g_base64_decode'
collect2: error: ld returned 1 exit status
Makefile:386: recipe for target 'cifsd' failed
```

**Comment by sergey-senozhatsky** [comment]
> mhh your patch made cifsd actually bigger, compared to a full static build?

lol... bummer!

Hmm, maybe what you currently have is the best option (all things considered).
sed-ing pkg-config output is dirty and hacky (I guess).

> i get errors with missing calls into gio-2.0?

Hmm. Is gio a separate library? Or it is glibmm that we also should statically link?
Let me check. No, it seems that glibmm has nothing to do with it:

```
readelf -a /usr/lib/x86_64-linux-gnu/libglib-2.0.so
[..]
   712: 0000000000070310   300 FUNC    GLOBAL DEFAULT   12 g_strrstr_len
   713: 0000000000050340    10 FUNC    GLOBAL DEFAULT   12 g_mapped_file_new_from_fd
   714: 0000000000054530    68 FUNC    GLOBAL DEFAULT   12 g_malloc0
[..]

```

`g_mapped_file_new_from_fd` is in glib-2.0 symbol table...
Do things look differently in your system?

What does `pkg-config --libs glib-2.0 --static` show?

-ss

**Comment by Andy2244** [comment]
```
readelf -a ./staging_dir/target-mipsel_24kc_musl/usr/lib/libglib-2.0.so | grep g_mapped_file_new_from_fd
  1490: 00047a14    32 FUNC    GLOBAL DEFAULT   11 g_mapped_file_new_from_fd
  2901: 00047a14    32 FUNC    GLOBAL DEFAULT   11 g_mapped_file_new_from_fd
```
```
readelf -a ./staging_dir/target-mipsel_24kc_musl/usr/lib/libglib-2.0.a | grep g_mapped_file_new_from_fd
    39: 000003b0    12 FUNC    GLOBAL DEFAULT    1 g_mapped_file_new_from_fd
```
Here is what our target glib2 install looks like:
[usr.tar.gz](https://github.com/cifsd-team/cifsd-tools/files/3950812/usr.tar.gz)

**Comment by Andy2244** [comment]
@sergey-senozhatsky Just as info, we managed to get the static cifsd binary down to 160kb or 100kb compressed by using more aggressive link options for cifsd + glib2.

```
CFLAGS += \
	-ffunction-sections \
	-fdata-sections \
	-flto
LDFLAGS += -Wl,--gc-sections,--as-needed
```

**Comment by Andy2244** [comment]
so this is now fixed for us

**Comment by sergey-senozhatsky** [comment]
> @sergey-senozhatsky Just as info, we managed to get the static cifsd binary down to 160kb or 100kb compressed by using more aggressive link options for cifsd + glib2.

Impressive!

-ss
