### ISSUE TITLE
Document default values.

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd-tools#78]
Hi, it would be great if the help file also lists the default values. 
We (openwrt) try to align our meta config values (UCI) with the upstream defaults, so for this checking the defaults via helpfile is quicker, compared to checking source.

I assume you get yours mainly from samba if its the same parameter?

**Comment by namjaejeon** [comment]
> I assume you get yours mainly from samba if its the same parameter?
Almost same, but some of ones are different. I can divide smb.conf.example with parameter list file.

How do you think this format fpr new parameter list file ?

- read only (section : share, default : yes)
  If this parameter is yes, then users of a service may not
  create or modify files in the service's directory.

- browseable (section : share, default : yes)
  This controls whether this share is seen in the list of
   available shares in a net view and in the browse list.

**Comment by Andy2244** [comment]
Looks fine, i'm just happy to have a file i can search for the option name directly, since in source you convert to c defines, so its harder to search for.

**Comment by Andy2244** [comment]
thanks
