### ISSUE TITLE
'read only = no' not working?

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/cifsd-tools#79]
Cifsd Version 2.0.0 reboot-11562-g08d9c95417

This works under samba4, but not via cifsd? I cant get write access under cifsd for the share?

```
[global]
	netbios name = router
	server string = Cifsd on OpenWrt
	workgroup = WORKGROUP
	interfaces = br-lan 
	bind interfaces only = yes
	ipc timeout = 20
	deadtime = 15
	map to guest = Bad User

[test]
	path = /mnt/sda
	create mask = 0666
	directory mask = 0777
	read only = no
	guest ok = yes
```

If i replace `read only = no` with `writeable = yes` than it works? Yet both versions should work, since writeable is just a synonym?
Can you test/verify this problem?

**Comment by namjaejeon** [comment]
FIXED.

**Comment by Andy2244** [comment]
thanks verified its working now
